version: 2

models:
  - name: go_meeting_facts
    description: "Gold layer meeting analytics fact table with comprehensive meeting metrics"
    columns:
      - name: meeting_fact_id
        description: "Unique identifier for meeting fact records"
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "Reference to meeting identifier from silver layer"
        tests:
          - not_null
          - relationships:
              to: ref('si_meetings')
              field: meeting_id
      - name: host_id
        description: "Meeting host user identifier"
        tests:
          - not_null
      - name: meeting_topic
        description: "Cleaned and trimmed meeting topic"
      - name: start_time
        description: "Meeting start time in UTC"
        tests:
          - not_null
      - name: end_time
        description: "Meeting end time in UTC"
      - name: duration_minutes
        description: "Meeting duration in minutes"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1440
      - name: participant_count
        description: "Total number of participants"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      - name: engagement_score
        description: "Calculated engagement score (0-10)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 10
      - name: load_date
        description: "Date when record was loaded"
        tests:
          - not_null

  - name: go_participant_facts
    description: "Gold layer participant analytics fact table with detailed participant metrics"
    columns:
      - name: participant_fact_id
        description: "Unique identifier for participant fact records"
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "Reference to meeting identifier"
        tests:
          - not_null
      - name: participant_id
        description: "Reference to participant identifier from silver layer"
        tests:
          - not_null
          - relationships:
              to: ref('si_participants')
              field: participant_id
      - name: user_id
        description: "Reference to user identifier"
      - name: attendance_duration
        description: "Duration of participant attendance in minutes"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      - name: connection_quality_rating
        description: "Connection quality rating (1-5)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 5
      - name: load_date
        description: "Date when record was loaded"
        tests:
          - not_null

  - name: go_webinar_facts
    description: "Gold layer webinar analytics fact table with webinar performance metrics"
    columns:
      - name: webinar_fact_id
        description: "Unique identifier for webinar fact records"
        tests:
          - not_null
          - unique
      - name: webinar_id
        description: "Reference to webinar identifier from silver layer"
        tests:
          - not_null
          - relationships:
              to: ref('si_webinars')
              field: webinar_id
      - name: host_id
        description: "Webinar host user identifier"
        tests:
          - not_null
      - name: attendance_rate
        description: "Attendance rate percentage"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: engagement_score
        description: "Calculated engagement score (0-10)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 10
      - name: load_date
        description: "Date when record was loaded"
        tests:
          - not_null

  - name: go_billing_facts
    description: "Gold layer billing analytics fact table with financial transaction metrics"
    columns:
      - name: billing_fact_id
        description: "Unique identifier for billing fact records"
        tests:
          - not_null
          - unique
      - name: event_id
        description: "Reference to billing event identifier from silver layer"
        tests:
          - not_null
          - relationships:
              to: ref('si_billing_events')
              field: event_id
      - name: user_id
        description: "Reference to user identifier"
        tests:
          - not_null
      - name: amount
        description: "Transaction amount"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: currency_code
        description: "Currency code for transaction"
        tests:
          - accepted_values:
              values: ['USD', 'EUR', 'GBP', 'CAD']
      - name: load_date
        description: "Date when record was loaded"
        tests:
          - not_null

  - name: go_usage_facts
    description: "Gold layer usage analytics fact table with daily user activity metrics"
    columns:
      - name: usage_fact_id
        description: "Unique identifier for usage fact records"
        tests:
          - not_null
          - unique
      - name: user_id
        description: "Reference to user identifier"
        tests:
          - not_null
      - name: usage_date
        description: "Date of usage activity"
        tests:
          - not_null
      - name: meeting_count
        description: "Number of meetings hosted"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      - name: total_meeting_minutes
        description: "Total minutes of meetings hosted"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      - name: load_date
        description: "Date when record was loaded"
        tests:
          - not_null

  - name: go_quality_facts
    description: "Gold layer quality analytics fact table with connection and performance metrics"
    columns:
      - name: quality_fact_id
        description: "Unique identifier for quality fact records"
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "Reference to meeting identifier"
        tests:
          - not_null
      - name: participant_id
        description: "Reference to participant identifier"
        tests:
          - not_null
      - name: audio_quality_score
        description: "Audio quality score (1-10)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 10
      - name: video_quality_score
        description: "Video quality score (1-10)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 10
      - name: latency_ms
        description: "Connection latency in milliseconds"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1000
      - name: packet_loss_rate
        description: "Packet loss rate percentage"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: load_date
        description: "Date when record was loaded"
        tests:
          - not_null
