version: 2

models:
  - name: go_meeting_facts
    description: "Basic meeting facts table"
    
  - name: go_participant_facts
    description: "Basic participant facts table"
    
  - name: go_webinar_facts
    description: "Basic webinar facts table"
    
  - name: go_billing_facts
    description: "Basic billing facts table"
    
  - name: go_usage_facts
    description: "Basic usage facts table"
