version: 2

models:
  - name: go_process_audit
    description: "Gold layer process audit table for tracking ETL operations"
    columns:
      - name: execution_id
        description: "Unique identifier for each execution"
        data_type: varchar(50)
      - name: pipeline_name
        description: "Name of the pipeline being executed"
        data_type: varchar(200)
      - name: process_type
        description: "Type of process (DIMENSION_LOAD, FACT_LOAD, etc.)"
        data_type: varchar(100)
      - name: start_time
        description: "Process start timestamp"
        data_type: timestamp_ntz
      - name: end_time
        description: "Process end timestamp"
        data_type: timestamp_ntz
      - name: status
        description: "Process status (STARTED, COMPLETED, FAILED)"
        data_type: varchar(50)
      - name: error_message
        description: "Error message if process failed"
        data_type: varchar(2000)
      - name: records_processed
        description: "Number of records processed"
        data_type: number
      - name: records_successful
        description: "Number of records successfully processed"
        data_type: number
      - name: records_failed
        description: "Number of records that failed processing"
        data_type: number
      - name: processing_duration_seconds
        description: "Processing duration in seconds"
        data_type: number
      - name: source_system
        description: "Source system identifier"
        data_type: varchar(100)
      - name: target_system
        description: "Target system identifier"
        data_type: varchar(100)
      - name: user_executed
        description: "User who executed the process"
        data_type: varchar(100)
      - name: server_name
        description: "Server where process was executed"
        data_type: varchar(100)
      - name: memory_usage_mb
        description: "Memory usage in MB"
        data_type: number
      - name: cpu_usage_percent
        description: "CPU usage percentage"
        data_type: number(5,2)
      - name: data_volume_gb
        description: "Data volume processed in GB"
        data_type: number(10,2)
      - name: load_date
        description: "Date when record was loaded"
        data_type: date
      - name: update_date
        description: "Date when record was last updated"
        data_type: date

  - name: go_user_dimension
    description: "Gold layer user dimension table"
    columns:
      - name: user_dim_id
        description: "Surrogate key for user dimension"
        data_type: varchar(50)
      - name: user_id
        description: "Natural key - user identifier"
        data_type: varchar(50)
      - name: user_name
        description: "User display name"
        data_type: varchar(255)
      - name: email_address
        description: "User email address"
        data_type: varchar(320)
      - name: user_type
        description: "Type of user (Professional, Basic, Enterprise, Standard)"
        data_type: varchar(50)
      - name: account_status
        description: "Account status (Active, Inactive, Unknown)"
        data_type: varchar(50)
      - name: license_type
        description: "License type assigned to user"
        data_type: varchar(100)
      - name: department_name
        description: "Department name"
        data_type: varchar(200)
      - name: job_title
        description: "Job title"
        data_type: varchar(200)
      - name: time_zone
        description: "User time zone"
        data_type: varchar(50)
      - name: account_creation_date
        description: "Account creation date"
        data_type: date
      - name: last_login_date
        description: "Last login date"
        data_type: date
      - name: language_preference
        description: "Language preference"
        data_type: varchar(50)
      - name: phone_number
        description: "Phone number"
        data_type: varchar(50)
      - name: load_date
        description: "Date when record was loaded"
        data_type: date
      - name: update_date
        description: "Date when record was last updated"
        data_type: date
      - name: source_system
        description: "Source system identifier"
        data_type: varchar(100)

  - name: go_time_dimension
    description: "Gold layer time dimension table"
    columns:
      - name: time_dim_id
        description: "Surrogate key for time dimension"
        data_type: varchar(50)
      - name: date_key
        description: "Natural key - date value"
        data_type: date
      - name: year_number
        description: "Year number"
        data_type: number
      - name: quarter_number
        description: "Quarter number (1-4)"
        data_type: number
      - name: month_number
        description: "Month number (1-12)"
        data_type: number
      - name: month_name
        description: "Month name"
        data_type: varchar(20)
      - name: week_number
        description: "Week number of year"
        data_type: number
      - name: day_of_year
        description: "Day of year (1-366)"
        data_type: number
      - name: day_of_month
        description: "Day of month (1-31)"
        data_type: number
      - name: day_of_week
        description: "Day of week (0-6, Sunday=0)"
        data_type: number
      - name: day_name
        description: "Day name"
        data_type: varchar(20)
      - name: is_weekend
        description: "Boolean flag for weekend"
        data_type: boolean
      - name: is_holiday
        description: "Boolean flag for holiday"
        data_type: boolean
      - name: fiscal_year
        description: "Fiscal year"
        data_type: number
      - name: fiscal_quarter
        description: "Fiscal quarter"
        data_type: number
      - name: load_date
        description: "Date when record was loaded"
        data_type: date
      - name: update_date
        description: "Date when record was last updated"
        data_type: date
      - name: source_system
        description: "Source system identifier"
        data_type: varchar(100)

  - name: go_meeting_facts
    description: "Gold layer meeting facts table"
    columns:
      - name: meeting_fact_id
        description: "Unique identifier for meeting fact"
        data_type: varchar(50)
      - name: meeting_id
        description: "Meeting identifier"
        data_type: varchar(50)
      - name: host_id
        description: "Host user identifier"
        data_type: varchar(50)
      - name: meeting_topic
        description: "Meeting topic/title"
        data_type: varchar(500)
      - name: start_time
        description: "Meeting start timestamp"
        data_type: timestamp_ntz
      - name: end_time
        description: "Meeting end timestamp"
        data_type: timestamp_ntz
      - name: duration_minutes
        description: "Meeting duration in minutes"
        data_type: number
      - name: participant_count
        description: "Number of participants"
        data_type: number
      - name: max_concurrent_participants
        description: "Maximum concurrent participants"
        data_type: number
      - name: total_attendance_minutes
        description: "Total attendance minutes across all participants"
        data_type: number
      - name: average_attendance_duration
        description: "Average attendance duration per participant"
        data_type: number
      - name: meeting_type
        description: "Meeting type (Quick, Standard, Extended)"
        data_type: varchar(50)
      - name: meeting_status
        description: "Meeting status (Completed, In Progress, Scheduled)"
        data_type: varchar(50)
      - name: recording_enabled
        description: "Boolean flag for recording enabled"
        data_type: boolean
      - name: screen_share_count
        description: "Number of screen share sessions"
        data_type: number
      - name: chat_message_count
        description: "Number of chat messages"
        data_type: number
      - name: breakout_room_count
        description: "Number of breakout rooms"
        data_type: number
      - name: quality_score_avg
        description: "Average quality score"
        data_type: number(5,2)
      - name: engagement_score
        description: "Calculated engagement score"
        data_type: number(5,2)
      - name: load_date
        description: "Date when record was loaded"
        data_type: date
      - name: update_date
        description: "Date when record was last updated"
        data_type: date
      - name: source_system
        description: "Source system identifier"
        data_type: varchar(100)

  - name: go_participant_facts
    description: "Gold layer participant facts table"
    columns:
      - name: participant_fact_id
        description: "Unique identifier for participant fact"
        data_type: varchar(50)
      - name: meeting_id
        description: "Meeting identifier"
        data_type: varchar(50)
      - name: participant_id
        description: "Participant identifier"
        data_type: varchar(50)
      - name: user_id
        description: "User identifier"
        data_type: varchar(50)
      - name: join_time
        description: "Participant join timestamp"
        data_type: timestamp_ntz
      - name: leave_time
        description: "Participant leave timestamp"
        data_type: timestamp_ntz
      - name: attendance_duration
        description: "Attendance duration in minutes"
        data_type: number
      - name: participant_role
        description: "Participant role (Host, Participant)"
        data_type: varchar(50)
      - name: audio_connection_type
        description: "Audio connection type"
        data_type: varchar(50)
      - name: video_enabled
        description: "Boolean flag for video enabled"
        data_type: boolean
      - name: screen_share_duration
        description: "Screen share duration"
        data_type: number
      - name: chat_messages_sent
        description: "Number of chat messages sent"
        data_type: number
      - name: interaction_count
        description: "Total interaction count"
        data_type: number
      - name: connection_quality_rating
        description: "Connection quality rating"
        data_type: number(3,2)
      - name: device_type
        description: "Device type used"
        data_type: varchar(100)
      - name: geographic_location
        description: "Geographic location"
        data_type: varchar(100)
      - name: load_date
        description: "Date when record was loaded"
        data_type: date
      - name: update_date
        description: "Date when record was last updated"
        data_type: date
      - name: source_system
        description: "Source system identifier"
        data_type: varchar(100)

  - name: go_webinar_facts
    description: "Gold layer webinar facts table"
    columns:
      - name: webinar_fact_id
        description: "Unique identifier for webinar fact"
        data_type: varchar(50)
      - name: webinar_id
        description: "Webinar identifier"
        data_type: varchar(50)
      - name: host_id
        description: "Host user identifier"
        data_type: varchar(50)
      - name: webinar_topic
        description: "Webinar topic/title"
        data_type: varchar(500)
      - name: start_time
        description: "Webinar start timestamp"
        data_type: timestamp_ntz
      - name: end_time
        description: "Webinar end timestamp"
        data_type: timestamp_ntz
      - name: duration_minutes
        description: "Webinar duration in minutes"
        data_type: number
      - name: registrants_count
        description: "Number of registrants"
        data_type: number
      - name: actual_attendees
        description: "Number of actual attendees"
        data_type: number
      - name: attendance_rate
        description: "Attendance rate percentage"
        data_type: number(5,2)
      - name: max_concurrent_attendees
        description: "Maximum concurrent attendees"
        data_type: number
      - name: qa_questions_count
        description: "Number of Q&A questions"
        data_type: number
      - name: poll_responses_count
        description: "Number of poll responses"
        data_type: number
      - name: engagement_score
        description: "Calculated engagement score"
        data_type: number(5,2)
      - name: event_category
        description: "Event category (Long Form, Standard, Short Form)"
        data_type: varchar(100)
      - name: load_date
        description: "Date when record was loaded"
        data_type: date
      - name: update_date
        description: "Date when record was last updated"
        data_type: date
      - name: source_system
        description: "Source system identifier"
        data_type: varchar(100)

  - name: go_billing_facts
    description: "Gold layer billing facts table"
    columns:
      - name: billing_fact_id
        description: "Unique identifier for billing fact"
        data_type: varchar(50)
      - name: event_id
        description: "Billing event identifier"
        data_type: varchar(50)
      - name: user_id
        description: "User identifier"
        data_type: varchar(50)
      - name: organization_id
        description: "Organization identifier"
        data_type: varchar(50)
      - name: event_type
        description: "Billing event type"
        data_type: varchar(100)
      - name: amount
        description: "Billing amount"
        data_type: number(10,2)
      - name: event_date
        description: "Billing event date"
        data_type: date
      - name: billing_period_start
        description: "Billing period start date"
        data_type: date
      - name: billing_period_end
        description: "Billing period end date"
        data_type: date
      - name: payment_method
        description: "Payment method"
        data_type: varchar(50)
      - name: transaction_status
        description: "Transaction status"
        data_type: varchar(50)
      - name: currency_code
        description: "Currency code"
        data_type: varchar(10)
      - name: tax_amount
        description: "Tax amount"
        data_type: number(10,2)
      - name: discount_amount
        description: "Discount amount"
        data_type: number(10,2)
      - name: load_date
        description: "Date when record was loaded"
        data_type: date
      - name: update_date
        description: "Date when record was last updated"
        data_type: date
      - name: source_system
        description: "Source system identifier"
        data_type: varchar(100)

  - name: go_usage_facts
    description: "Gold layer usage facts table"
    columns:
      - name: usage_fact_id
        description: "Unique identifier for usage fact"
        data_type: varchar(50)
      - name: user_id
        description: "User identifier"
        data_type: varchar(50)
      - name: organization_id
        description: "Organization identifier"
        data_type: varchar(50)
      - name: usage_date
        description: "Usage date"
        data_type: date
      - name: meeting_count
        description: "Number of meetings"
        data_type: number
      - name: total_meeting_minutes
        description: "Total meeting minutes"
        data_type: number
      - name: webinar_count
        description: "Number of webinars"
        data_type: number
      - name: total_webinar_minutes
        description: "Total webinar minutes"
        data_type: number
      - name: recording_storage_gb
        description: "Recording storage in GB"
        data_type: number(10,2)
      - name: feature_usage_count
        description: "Feature usage count"
        data_type: number
      - name: unique_participants_hosted
        description: "Unique participants hosted"
        data_type: number
      - name: load_date
        description: "Date when record was loaded"
        data_type: date
      - name: update_date
        description: "Date when record was last updated"
        data_type: date
      - name: source_system
        description: "Source system identifier"
        data_type: varchar(100)
