version: 2

sources:
  - name: silver
    description: "Silver layer tables containing cleaned and validated data"
    tables:
      - name: si_users
        description: "Silver users table"
      - name: si_meetings
        description: "Silver meetings table"
      - name: si_participants
        description: "Silver participants table"
      - name: si_feature_usage
        description: "Silver feature usage table"
      - name: si_webinars
        description: "Silver webinars table"
      - name: si_support_tickets
        description: "Silver support tickets table"
      - name: si_licenses
        description: "Silver licenses table"
      - name: si_billing_events
        description: "Silver billing events table"
