name: 'Zoom_Customer_Analytics'
version: '1.0.0'
config-version: 2

profile: 'zoom_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  Zoom_Customer_Analytics:
    +materialized: table
    gold:
      +materialized: table
      fact:
        +materialized: table
        +cluster_by: ["load_date"]
      dimensional:
        +materialized: table
        +cluster_by: ["load_date"]
      aggregated:
        +materialized: table
        +cluster_by: ["load_date"]
    silver:
      +materialized: table
    bronze:
      +materialized: table

vars:
  # Global variables
  start_date: '2020-01-01'
  end_date: '2030-12-31'
  
on-run-start:
  - "{{ log('Starting DBT run for Zoom Customer Analytics', info=true) }}"

on-run-end:
  - "{{ log('Completed DBT run for Zoom Customer Analytics', info=true) }}"
