name: 'Zoom_Customer_Analytics'
version: '1.0.0'
config-version: 2

profile: 'Zoom_Customer_Analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  Zoom_Customer_Analytics:
    bronze:
      +materialized: table
    silver:
      +materialized: incremental
      +on_schema_change: "fail"
    gold:
      +materialized: table

vars:
  start_date: '2020-01-01'
  end_date: '2030-12-31'
