name: 'Zoom_Customer_Analytics'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  Zoom_Customer_Analytics:
    gold:
      +materialized: table
      dimension:
        +materialized: table
        +pre-hook: |
          {% if this.name != 'go_process_audit' %}
            INSERT INTO {{ ref('go_process_audit') }} (
              execution_id, pipeline_name, process_type, start_time, status,
              source_system, target_system, user_executed, load_date
            )
            VALUES (
              '{{ invocation_id }}',
              '{{ this.name }}',
              'DIMENSION_LOAD',
              CURRENT_TIMESTAMP(),
              'STARTED',
              'SILVER',
              'GOLD',
              'DBT_CLOUD',
              CURRENT_DATE()
            )
          {% endif %}
        +post-hook: |
          {% if this.name != 'go_process_audit' %}
            UPDATE {{ ref('go_process_audit') }}
            SET end_time = CURRENT_TIMESTAMP(),
                status = 'COMPLETED',
                records_processed = (SELECT COUNT(*) FROM {{ this }}),
                processing_duration_seconds = DATEDIFF('second', start_time, CURRENT_TIMESTAMP())
            WHERE execution_id = '{{ invocation_id }}'
              AND pipeline_name = '{{ this.name }}'
          {% endif %}
