name: 'zoom_customer_analytics'
version: '1.0.0'
config-version: 2

profile: 'snowflake_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_customer_analytics:
    +materialized: table
    gold:
      fact:
        +materialized: incremental
        +unique_key: 'fact_key'
        +on_schema_change: 'sync_all_columns'

vars:
  start_date: '2020-01-01'
  timezone: 'UTC'
