name: 'Zoom_Customer_Analytics'
version: '1.0.0'
config-version: 2

profile: 'zoom_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  Zoom_Customer_Analytics:
    +materialized: table
    bronze:
      +materialized: view
    silver:
      +materialized: incremental
      +on_schema_change: sync_all_columns
    gold:
      +materialized: table
      fact:
        +materialized: incremental
        +on_schema_change: sync_all_columns
        +unique_key: "{{ this.name }}_id"
      dimensional:
        +materialized: table

vars:
  # dbt-date variables
  "dbt_date:time_zone": "UTC"
