version: 2

models:
  - name: go_user_dimension
    description: "Gold layer user dimension table containing comprehensive user information"
    columns:
      - name: user_dim_id
        description: "Surrogate key for user dimension"
        tests:
          - not_null
          - unique
      - name: user_id
        description: "Natural key - unique identifier for user from source system"
        tests:
          - not_null
          - unique
      - name: user_name
        description: "User display name"
        tests:
          - not_null
      - name: email_address
        description: "User email address"
        tests:
          - not_null
      - name: user_type
        description: "User subscription type (Professional, Basic, Enterprise, Standard)"
        tests:
          - not_null
          - accepted_values:
              values: ['Professional', 'Basic', 'Enterprise', 'Standard']
      - name: account_status
        description: "User account status (Active, Inactive, Unknown)"
        tests:
          - not_null
          - accepted_values:
              values: ['Active', 'Inactive', 'Unknown']
      - name: license_type
        description: "Current license type assigned to user"
      - name: department_name
        description: "User department name"
      - name: job_title
        description: "User job title"
      - name: time_zone
        description: "User time zone preference"
      - name: account_creation_date
        description: "Date when user account was created"
      - name: last_login_date
        description: "Date of user's last login"
      - name: language_preference
        description: "User's preferred language"
      - name: phone_number
        description: "User's phone number"
      - name: load_date
        description: "Date when record was loaded into Gold layer"
        tests:
          - not_null
      - name: update_date
        description: "Date when record was last updated in Gold layer"
        tests:
          - not_null
      - name: source_system
        description: "Source system identifier"
        tests:
          - not_null

  - name: go_time_dimension
    description: "Gold layer time dimension table containing date hierarchy and attributes"
    columns:
      - name: time_dim_id
        description: "Surrogate key for time dimension"
        tests:
          - not_null
          - unique
      - name: date_key
        description: "Natural key - date value"
        tests:
          - not_null
          - unique
      - name: year_number
        description: "Year number (e.g., 2024)"
        tests:
          - not_null
      - name: quarter_number
        description: "Quarter number (1-4)"
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4]
      - name: month_number
        description: "Month number (1-12)"
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
      - name: month_name
        description: "Month name (January, February, etc.)"
        tests:
          - not_null
      - name: week_number
        description: "Week number of the year (1-53)"
        tests:
          - not_null
      - name: day_of_year
        description: "Day of year (1-366)"
        tests:
          - not_null
      - name: day_of_month
        description: "Day of month (1-31)"
        tests:
          - not_null
      - name: day_of_week
        description: "Day of week (0=Sunday, 6=Saturday)"
        tests:
          - not_null
          - accepted_values:
              values: [0, 1, 2, 3, 4, 5, 6]
      - name: day_name
        description: "Day name (Sunday, Monday, etc.)"
        tests:
          - not_null
      - name: is_weekend
        description: "Boolean flag indicating if date is weekend"
        tests:
          - not_null
      - name: is_holiday
        description: "Boolean flag indicating if date is holiday"
        tests:
          - not_null
      - name: fiscal_year
        description: "Fiscal year number"
        tests:
          - not_null
      - name: fiscal_quarter
        description: "Fiscal quarter number (1-4)"
        tests:
          - not_null
      - name: load_date
        description: "Date when record was loaded into Gold layer"
        tests:
          - not_null
      - name: update_date
        description: "Date when record was last updated in Gold layer"
        tests:
          - not_null
      - name: source_system
        description: "Source system identifier"
        tests:
          - not_null

  - name: go_process_audit
    description: "Gold layer process audit table for tracking ETL execution"
    columns:
      - name: execution_id
        description: "Unique identifier for execution"
        tests:
          - not_null
      - name: pipeline_name
        description: "Name of the pipeline being executed"
        tests:
          - not_null
      - name: process_type
        description: "Type of process (DIMENSION_LOAD, FACT_LOAD, etc.)"
        tests:
          - not_null
      - name: start_time
        description: "Process start timestamp"
        tests:
          - not_null
      - name: end_time
        description: "Process end timestamp"
      - name: status
        description: "Process status (STARTED, RUNNING, COMPLETED, FAILED)"
        tests:
          - not_null
          - accepted_values:
              values: ['STARTED', 'RUNNING', 'COMPLETED', 'FAILED']
      - name: error_message
        description: "Error message if process failed"
      - name: records_processed
        description: "Number of records processed"
      - name: records_successful
        description: "Number of records successfully processed"
      - name: records_failed
        description: "Number of records that failed processing"
      - name: processing_duration_seconds
        description: "Processing duration in seconds"
      - name: source_system
        description: "Source system identifier"
        tests:
          - not_null
      - name: target_system
        description: "Target system identifier"
        tests:
          - not_null
      - name: user_executed
        description: "User who executed the process"
      - name: server_name
        description: "Server where process was executed"
      - name: memory_usage_mb
        description: "Memory usage in MB"
      - name: cpu_usage_percent
        description: "CPU usage percentage"
      - name: data_volume_gb
        description: "Data volume processed in GB"
      - name: load_date
        description: "Date when record was loaded"
        tests:
          - not_null
      - name: update_date
        description: "Date when record was last updated"
        tests:
          - not_null
