version: 2

models:
  - name: go_user_dimension
    description: "Gold layer user dimension table with comprehensive user attributes"
    columns:
      - name: user_dim_id
        description: "Surrogate key for user dimension"
        data_type: varchar(255)
        tests:
          - unique
          - not_null
      - name: user_id
        description: "Natural key - unique user identifier from source"
        data_type: varchar(255)
        tests:
          - not_null
      - name: user_name
        description: "User display name"
        data_type: varchar(255)
      - name: email_address
        description: "User email address"
        data_type: varchar(320)
      - name: user_type
        description: "User type based on plan"
        data_type: varchar(50)
      - name: account_status
        description: "Account status"
        data_type: varchar(50)
      - name: license_type
        description: "License type assigned to user"
        data_type: varchar(100)
      - name: department_name
        description: "Department or company name"
        data_type: varchar(200)
      - name: job_title
        description: "User job title"
        data_type: varchar(200)
      - name: time_zone
        description: "User time zone"
        data_type: varchar(50)
      - name: account_creation_date
        description: "Account creation date"
        data_type: date
      - name: last_login_date
        description: "Last login date"
        data_type: date
      - name: language_preference
        description: "User language preference"
        data_type: varchar(50)
      - name: phone_number
        description: "User phone number"
        data_type: varchar(50)
      - name: load_date
        description: "Data load date"
        data_type: date
      - name: update_date
        description: "Data update date"
        data_type: date
      - name: source_system
        description: "Source system identifier"
        data_type: varchar(100)

  - name: go_time_dimension
    description: "Gold layer time dimension table with comprehensive date attributes"
    columns:
      - name: time_dim_id
        description: "Surrogate key for time dimension"
        data_type: varchar(255)
        tests:
          - unique
          - not_null
      - name: date_key
        description: "Natural key - date value"
        data_type: date
        tests:
          - unique
          - not_null
      - name: year_number
        description: "Year number"
        data_type: number
      - name: quarter_number
        description: "Quarter number (1-4)"
        data_type: number
      - name: month_number
        description: "Month number (1-12)"
        data_type: number
      - name: month_name
        description: "Month name"
        data_type: varchar(20)
      - name: week_number
        description: "Week number of year"
        data_type: number
      - name: day_of_year
        description: "Day of year (1-366)"
        data_type: number
      - name: day_of_month
        description: "Day of month (1-31)"
        data_type: number
      - name: day_of_week
        description: "Day of week (0-6, Sunday=0)"
        data_type: number
      - name: day_name
        description: "Day name"
        data_type: varchar(20)
      - name: is_weekend
        description: "Weekend flag"
        data_type: boolean
      - name: is_holiday
        description: "Holiday flag"
        data_type: boolean
      - name: fiscal_year
        description: "Fiscal year"
        data_type: number
      - name: fiscal_quarter
        description: "Fiscal quarter"
        data_type: number

  - name: go_organization_dimension
    description: "Gold layer organization dimension table"
    columns:
      - name: organization_dim_id
        description: "Surrogate key for organization dimension"
        data_type: varchar(255)
        tests:
          - unique
          - not_null
      - name: organization_id
        description: "Natural key - organization identifier"
        data_type: varchar(255)
      - name: organization_name
        description: "Organization name"
        data_type: varchar(500)
      - name: industry_classification
        description: "Industry classification"
        data_type: varchar(200)
      - name: organization_size
        description: "Organization size category"
        data_type: varchar(50)
      - name: primary_contact_email
        description: "Primary contact email"
        data_type: varchar(320)
      - name: billing_address
        description: "Billing address"
        data_type: varchar(1000)
      - name: account_manager_name
        description: "Account manager name"
        data_type: varchar(255)
      - name: contract_start_date
        description: "Contract start date"
        data_type: date
      - name: contract_end_date
        description: "Contract end date"
        data_type: date
      - name: maximum_user_limit
        description: "Maximum user limit"
        data_type: number
      - name: storage_quota_gb
        description: "Storage quota in GB"
        data_type: number
      - name: security_policy_level
        description: "Security policy level"
        data_type: varchar(100)

  - name: go_device_dimension
    description: "Gold layer device dimension table"
    columns:
      - name: device_dim_id
        description: "Surrogate key for device dimension"
        data_type: varchar(255)
        tests:
          - unique
          - not_null
      - name: device_connection_id
        description: "Device connection identifier"
        data_type: varchar(255)
      - name: device_type
        description: "Device type"
        data_type: varchar(100)
      - name: operating_system
        description: "Operating system"
        data_type: varchar(100)
      - name: application_version
        description: "Application version"
        data_type: varchar(50)
      - name: network_connection_type
        description: "Network connection type"
        data_type: varchar(50)
      - name: device_category
        description: "Device category"
        data_type: varchar(50)
      - name: platform_family
        description: "Platform family"
        data_type: varchar(50)

  - name: go_geography_dimension
    description: "Gold layer geography dimension table"
    columns:
      - name: geography_dim_id
        description: "Surrogate key for geography dimension"
        data_type: varchar(255)
        tests:
          - unique
          - not_null
      - name: country_code
        description: "Country code"
        data_type: varchar(10)
      - name: country_name
        description: "Country name"
        data_type: varchar(100)
      - name: region_name
        description: "Region name"
        data_type: varchar(100)
      - name: time_zone
        description: "Time zone"
        data_type: varchar(50)
      - name: continent
        description: "Continent name"
        data_type: varchar(50)
