SELECT 
    'PF_001' AS participant_fact_id,
    'MEETING_001' AS meeting_id,
    'PARTICIPANT_001' AS participant_id,
    'USER_001' AS user_id,
    '2024-01-01 10:00:00'::TIMESTAMP AS join_time,
    '2024-01-01 10:45:00'::TIMESTAMP AS leave_time,
    45 AS attendance_duration,
    'Participant' AS participant_role,
    'Computer Audio' AS audio_connection_type,
    TRUE AS video_enabled,
    5 AS screen_share_duration,
    3 AS chat_messages_sent,
    8 AS interaction_count,
    8.2 AS connection_quality_rating,
    'Desktop' AS device_type,
    'US-East' AS geographic_location,
    '2024-01-01'::DATE AS load_date,
    '2024-01-01'::DATE AS update_date,
    'ZOOM_API' AS source_system
WHERE 1=0
