version: 2

models:
  - name: go_meeting_facts
    description: "Gold layer fact table containing meeting analytics and metrics"
    columns:
      - name: meeting_fact_id
        description: "Unique identifier for meeting fact record"
        tests:
          - unique
          - not_null
      - name: meeting_id
        description: "Meeting identifier from source system"
        tests:
          - not_null
      - name: host_id
        description: "Host user identifier"
      - name: meeting_topic
        description: "Meeting topic or subject"
      - name: start_time
        description: "Meeting start timestamp in UTC"
      - name: end_time
        description: "Meeting end timestamp in UTC"
      - name: duration_minutes
        description: "Meeting duration in minutes"
      - name: participant_count
        description: "Total number of participants"
      - name: engagement_score
        description: "Calculated engagement score based on interactions"
      - name: load_date
        description: "Date when record was loaded"
      - name: update_date
        description: "Date when record was last updated"
      - name: source_system
        description: "Source system identifier"

  - name: go_participant_facts
    description: "Gold layer fact table containing participant-level meeting data"
    columns:
      - name: participant_fact_id
        description: "Unique identifier for participant fact record"
        tests:
          - unique
          - not_null
      - name: meeting_id
        description: "Meeting identifier"
        tests:
          - not_null
      - name: participant_id
        description: "Participant identifier"
        tests:
          - not_null
      - name: user_id
        description: "User identifier"
      - name: join_time
        description: "Participant join timestamp"
      - name: leave_time
        description: "Participant leave timestamp"
      - name: attendance_duration
        description: "Duration of participation in minutes"
      - name: participant_role
        description: "Role of participant (Host/Participant)"
      - name: connection_quality_rating
        description: "Connection quality score"

  - name: go_webinar_facts
    description: "Gold layer fact table containing webinar analytics"
    columns:
      - name: webinar_fact_id
        description: "Unique identifier for webinar fact record"
        tests:
          - unique
          - not_null
      - name: webinar_id
        description: "Webinar identifier"
        tests:
          - not_null
      - name: host_id
        description: "Webinar host identifier"
      - name: webinar_topic
        description: "Webinar topic or subject"
      - name: registrants_count
        description: "Number of registered attendees"
      - name: actual_attendees
        description: "Number of actual attendees"
      - name: attendance_rate
        description: "Attendance rate percentage"
      - name: engagement_score
        description: "Webinar engagement score"

  - name: go_billing_facts
    description: "Gold layer fact table containing billing and transaction data"
    columns:
      - name: billing_fact_id
        description: "Unique identifier for billing fact record"
        tests:
          - unique
          - not_null
      - name: event_id
        description: "Billing event identifier"
        tests:
          - not_null
      - name: user_id
        description: "User identifier"
      - name: organization_id
        description: "Organization identifier"
      - name: event_type
        description: "Type of billing event"
      - name: amount
        description: "Transaction amount"
      - name: event_date
        description: "Date of billing event"
      - name: transaction_status
        description: "Status of transaction"

  - name: go_usage_facts
    description: "Gold layer fact table containing user usage metrics"
    columns:
      - name: usage_fact_id
        description: "Unique identifier for usage fact record"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "User identifier"
        tests:
          - not_null
      - name: organization_id
        description: "Organization identifier"
      - name: usage_date
        description: "Date of usage"
      - name: meeting_count
        description: "Number of meetings hosted"
      - name: total_meeting_minutes
        description: "Total meeting minutes"
      - name: webinar_count
        description: "Number of webinars hosted"
      - name: feature_usage_count
        description: "Total feature usage count"

  - name: go_quality_facts
    description: "Gold layer fact table containing quality metrics"
    columns:
      - name: quality_fact_id
        description: "Unique identifier for quality fact record"
        tests:
          - unique
          - not_null
      - name: meeting_id
        description: "Meeting identifier"
        tests:
          - not_null
      - name: participant_id
        description: "Participant identifier"
        tests:
          - not_null
      - name: audio_quality_score
        description: "Audio quality score"
      - name: video_quality_score
        description: "Video quality score"
      - name: connection_stability_rating
        description: "Connection stability rating"
      - name: latency_ms
        description: "Connection latency in milliseconds"
      - name: packet_loss_rate
        description: "Packet loss rate"
