version: 2

models:
  - name: go_meeting_facts
    description: "Gold layer fact table containing meeting analytics and metrics"
    columns:
      - name: meeting_fact_id
        description: "Unique identifier for meeting fact record"
        tests:
          - unique
          - not_null
      - name: meeting_id
        description: "Meeting identifier from source system"
        tests:
          - not_null
      - name: host_id
        description: "Host user identifier"
        tests:
          - not_null
      - name: meeting_topic
        description: "Meeting topic or subject"
      - name: start_time
        description: "Meeting start timestamp in UTC"
        tests:
          - not_null
      - name: end_time
        description: "Meeting end timestamp in UTC"
      - name: duration_minutes
        description: "Meeting duration in minutes"
        tests:
          - not_null
      - name: participant_count
        description: "Total number of participants"
      - name: engagement_score
        description: "Calculated engagement score based on interactions"
      - name: quality_score_avg
        description: "Average quality score for the meeting"

  - name: go_participant_facts
    description: "Gold layer fact table containing participant engagement metrics"
    columns:
      - name: participant_fact_id
        description: "Unique identifier for participant fact record"
        tests:
          - unique
          - not_null
      - name: meeting_id
        description: "Meeting identifier"
        tests:
          - not_null
      - name: participant_id
        description: "Participant identifier"
        tests:
          - not_null
      - name: user_id
        description: "User identifier"
      - name: attendance_duration
        description: "Duration of participant attendance in minutes"
      - name: participant_role
        description: "Role of participant (Host/Participant)"
      - name: connection_quality_rating
        description: "Connection quality rating"

  - name: go_webinar_facts
    description: "Gold layer fact table containing webinar analytics and metrics"
    columns:
      - name: webinar_fact_id
        description: "Unique identifier for webinar fact record"
        tests:
          - unique
          - not_null
      - name: webinar_id
        description: "Webinar identifier"
        tests:
          - not_null
      - name: host_id
        description: "Webinar host identifier"
        tests:
          - not_null
      - name: registrants_count
        description: "Number of registered attendees"
      - name: actual_attendees
        description: "Number of actual attendees"
      - name: attendance_rate
        description: "Attendance rate percentage"
      - name: engagement_score
        description: "Webinar engagement score"

  - name: go_billing_facts
    description: "Gold layer fact table containing billing events and financial metrics"
    columns:
      - name: billing_fact_id
        description: "Unique identifier for billing fact record"
        tests:
          - unique
          - not_null
      - name: event_id
        description: "Billing event identifier"
        tests:
          - not_null
      - name: user_id
        description: "User identifier"
        tests:
          - not_null
      - name: organization_id
        description: "Organization identifier"
      - name: amount
        description: "Billing amount"
        tests:
          - not_null
      - name: event_date
        description: "Billing event date"
        tests:
          - not_null

  - name: go_usage_facts
    description: "Gold layer fact table containing user usage metrics and statistics"
    columns:
      - name: usage_fact_id
        description: "Unique identifier for usage fact record"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "User identifier"
        tests:
          - not_null
      - name: organization_id
        description: "Organization identifier"
      - name: usage_date
        description: "Usage date"
        tests:
          - not_null
      - name: meeting_count
        description: "Number of meetings hosted"
      - name: total_meeting_minutes
        description: "Total meeting minutes hosted"
      - name: feature_usage_count
        description: "Total feature usage count"

  - name: go_quality_facts
    description: "Gold layer fact table containing quality metrics and performance data"
    columns:
      - name: quality_fact_id
        description: "Unique identifier for quality fact record"
        tests:
          - unique
          - not_null
      - name: meeting_id
        description: "Meeting identifier"
        tests:
          - not_null
      - name: participant_id
        description: "Participant identifier"
        tests:
          - not_null
      - name: audio_quality_score
        description: "Audio quality score"
      - name: video_quality_score
        description: "Video quality score"
      - name: connection_stability_rating
        description: "Connection stability rating"
      - name: latency_ms
        description: "Connection latency in milliseconds"
