version: 2

models:
  - name: go_meeting_facts
    description: "Gold layer fact table containing comprehensive meeting analytics and metrics"
    columns:
      - name: meeting_fact_key
        description: "Unique surrogate key for each meeting fact record"
        tests:
          - unique
          - not_null
      - name: meeting_id
        description: "Unique identifier for the meeting"
        tests:
          - not_null
      - name: host_id
        description: "Unique identifier for the meeting host"
        tests:
          - not_null
      - name: duration_minutes
        description: "Meeting duration in minutes"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 1440
      - name: data_quality_score
        description: "Data quality score for the record"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 5
      - name: process_status
        description: "Processing status of the record"
        tests:
          - accepted_values:
              values: ['SUCCESS', 'ERROR', 'WARNING']

  - name: go_participant_facts
    description: "Gold layer fact table containing participant-level meeting analytics"
    columns:
      - name: participant_fact_key
        description: "Unique surrogate key for each participant fact record"
        tests:
          - unique
          - not_null
      - name: participant_id
        description: "Unique identifier for the participant record"
        tests:
          - not_null
      - name: meeting_id
        description: "Unique identifier for the meeting"
        tests:
          - not_null
      - name: user_id
        description: "Unique identifier for the user/participant"
        tests:
          - not_null
      - name: process_status
        description: "Processing status of the record"
        tests:
          - accepted_values:
              values: ['SUCCESS', 'ERROR', 'WARNING']

  - name: go_webinar_facts
    description: "Gold layer fact table containing webinar analytics and metrics"
    columns:
      - name: webinar_fact_key
        description: "Unique surrogate key for each webinar fact record"
        tests:
          - unique
          - not_null
      - name: webinar_id
        description: "Unique identifier for the webinar"
        tests:
          - not_null
      - name: host_id
        description: "Unique identifier for the webinar host"
        tests:
          - not_null
      - name: registrants
        description: "Number of webinar registrants"
        tests:
          - not_null
      - name: process_status
        description: "Processing status of the record"
        tests:
          - accepted_values:
              values: ['SUCCESS', 'ERROR', 'WARNING']

  - name: go_billing_facts
    description: "Gold layer fact table containing billing events and revenue analytics"
    columns:
      - name: billing_fact_key
        description: "Unique surrogate key for each billing fact record"
        tests:
          - unique
          - not_null
      - name: event_id
        description: "Unique identifier for the billing event"
        tests:
          - not_null
      - name: user_id
        description: "Unique identifier for the user"
        tests:
          - not_null
      - name: amount
        description: "Billing amount"
        tests:
          - not_null
      - name: process_status
        description: "Processing status of the record"
        tests:
          - accepted_values:
              values: ['SUCCESS', 'ERROR', 'WARNING']

  - name: go_usage_facts
    description: "Gold layer fact table containing feature usage analytics"
    columns:
      - name: usage_fact_key
        description: "Unique surrogate key for each usage fact record"
        tests:
          - unique
          - not_null
      - name: usage_id
        description: "Unique identifier for the usage record"
        tests:
          - not_null
      - name: meeting_id
        description: "Unique identifier for the meeting"
        tests:
          - not_null
      - name: feature_name
        description: "Name of the feature used"
        tests:
          - not_null
      - name: usage_count
        description: "Number of times the feature was used"
        tests:
          - not_null
      - name: process_status
        description: "Processing status of the record"
        tests:
          - accepted_values:
              values: ['SUCCESS', 'ERROR', 'WARNING']

  - name: go_quality_facts
    description: "Gold layer fact table containing quality metrics and support analytics"
    columns:
      - name: quality_fact_key
        description: "Unique surrogate key for each quality fact record"
        tests:
          - unique
          - not_null
      - name: ticket_id
        description: "Unique identifier for the support ticket"
        tests:
          - not_null
      - name: user_id
        description: "Unique identifier for the user"
        tests:
          - not_null
      - name: ticket_type
        description: "Type of support ticket"
        tests:
          - not_null
      - name: resolution_status
        description: "Status of ticket resolution"
        tests:
          - not_null
      - name: process_status
        description: "Processing status of the record"
        tests:
          - accepted_values:
              values: ['SUCCESS', 'ERROR', 'WARNING']
