version: 2

models:
  - name: go_meeting_facts
    description: "Gold layer fact table containing comprehensive meeting analytics and metrics"
    columns:
      - name: meeting_id
        description: "Unique identifier for each meeting"
        tests:
          - not_null
          - unique
      - name: host_id
        description: "Identifier for the meeting host"
        tests:
          - not_null
      - name: meeting_topic
        description: "Topic or title of the meeting"
      - name: start_time
        description: "Meeting start timestamp"
        tests:
          - not_null
      - name: end_time
        description: "Meeting end timestamp"
      - name: duration_minutes
        description: "Total meeting duration in minutes"
        tests:
          - not_null
      - name: total_participants
        description: "Total number of participants in the meeting"
      - name: avg_participation_duration_minutes
        description: "Average participation duration across all participants"
      - name: total_participation_minutes
        description: "Sum of all participant minutes"
      - name: features_used_count
        description: "Number of distinct features used in the meeting"
      - name: total_feature_usage
        description: "Total count of feature usage events"
      - name: participation_rate_percent
        description: "Calculated participation rate as percentage"
      - name: meeting_date
        description: "Date of the meeting"
      - name: meeting_hour
        description: "Hour when meeting started"
      - name: meeting_day_of_week
        description: "Day of week when meeting occurred"
      - name: data_quality_score
        description: "Data quality score for the record"
      - name: created_at
        description: "Record creation timestamp"
        tests:
          - not_null
      - name: updated_at
        description: "Record last update timestamp"
        tests:
          - not_null

  - name: go_participant_facts
    description: "Gold layer fact table containing participant-level meeting analytics"
    columns:
      - name: participant_id
        description: "Unique identifier for each participant record"
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "Reference to the meeting"
        tests:
          - not_null
      - name: user_id
        description: "Reference to the user/participant"
        tests:
          - not_null
      - name: join_time
        description: "When participant joined the meeting"
        tests:
          - not_null
      - name: leave_time
        description: "When participant left the meeting"
      - name: participation_duration_minutes
        description: "Duration of participation in minutes"
      - name: join_timeliness
        description: "Classification of join timing relative to meeting start"
        tests:
          - accepted_values:
              values: ['ON_TIME', 'SLIGHTLY_LATE', 'LATE']
      - name: leave_pattern
        description: "Classification of leave timing relative to meeting end"
        tests:
          - accepted_values:
              values: ['STAYED_FULL', 'LEFT_SLIGHTLY_EARLY', 'LEFT_EARLY']
      - name: attendance_percentage
        description: "Percentage of meeting time attended"

  - name: go_webinar_facts
    description: "Gold layer fact table containing webinar analytics and metrics"
    columns:
      - name: webinar_id
        description: "Unique identifier for each webinar"
        tests:
          - not_null
          - unique
      - name: host_id
        description: "Identifier for the webinar host"
        tests:
          - not_null
      - name: webinar_topic
        description: "Topic or title of the webinar"
      - name: start_time
        description: "Webinar start timestamp"
        tests:
          - not_null
      - name: end_time
        description: "Webinar end timestamp"
      - name: registrants
        description: "Number of registered participants"
        tests:
          - not_null
      - name: webinar_duration_minutes
        description: "Total webinar duration in minutes"
      - name: webinar_duration_category
        description: "Classification of webinar by duration"
        tests:
          - accepted_values:
              values: ['SHORT', 'MEDIUM', 'LONG', 'EXTENDED']
      - name: webinar_size_category
        description: "Classification of webinar by number of registrants"
        tests:
          - accepted_values:
              values: ['SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE']

  - name: go_billing_facts
    description: "Gold layer fact table containing billing events and revenue analytics"
    columns:
      - name: event_id
        description: "Unique identifier for each billing event"
        tests:
          - not_null
          - unique
      - name: user_id
        description: "Reference to the user associated with billing event"
        tests:
          - not_null
      - name: event_type
        description: "Type of billing event"
        tests:
          - not_null
      - name: amount
        description: "Billing amount"
        tests:
          - not_null
      - name: event_date
        description: "Date of the billing event"
        tests:
          - not_null
      - name: amount_category
        description: "Classification of billing amount"
        tests:
          - accepted_values:
              values: ['CREDIT_OR_FREE', 'LOW_VALUE', 'MEDIUM_VALUE', 'HIGH_VALUE', 'ENTERPRISE_VALUE']
      - name: revenue_category
        description: "Classification of revenue impact"
        tests:
          - accepted_values:
              values: ['RECURRING_REVENUE', 'EXPANSION_REVENUE', 'REVENUE_LOSS', 'OTHER_REVENUE']
      - name: net_revenue_impact
        description: "Net revenue impact considering refunds and chargebacks"

  - name: go_usage_facts
    description: "Gold layer fact table containing feature usage analytics"
    columns:
      - name: usage_id
        description: "Unique identifier for each usage record"
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "Reference to the meeting where feature was used"
        tests:
          - not_null
      - name: feature_name
        description: "Name of the feature used"
        tests:
          - not_null
      - name: usage_count
        description: "Number of times feature was used"
        tests:
          - not_null
      - name: usage_date
        description: "Date when feature was used"
        tests:
          - not_null
      - name: feature_category
        description: "Classification of feature type"
        tests:
          - accepted_values:
              values: ['COLLABORATION', 'ENGAGEMENT', 'CONTENT_MANAGEMENT', 'MEETING_MANAGEMENT', 'OTHER']
      - name: usage_intensity
        description: "Classification of usage frequency"
        tests:
          - accepted_values:
              values: ['SINGLE_USE', 'LOW_USAGE', 'MODERATE_USAGE', 'HIGH_USAGE', 'INTENSIVE_USAGE']
      - name: usage_per_hour
        description: "Calculated usage frequency per hour"

  - name: go_quality_facts
    description: "Gold layer fact table containing data quality and support analytics"
    columns:
      - name: ticket_id
        description: "Unique identifier for each support ticket"
        tests:
          - not_null
          - unique
      - name: user_id
        description: "Reference to the user who created the ticket"
        tests:
          - not_null
      - name: ticket_type
        description: "Type of support ticket"
        tests:
          - not_null
      - name: resolution_status
        description: "Current status of the ticket"
        tests:
          - not_null
      - name: open_date
        description: "Date when ticket was opened"
        tests:
          - not_null
      - name: issue_category
        description: "Classification of issue type"
        tests:
          - accepted_values:
              values: ['TECHNICAL_QUALITY', 'USER_EXPERIENCE', 'ACCOUNT_MANAGEMENT', 'OTHER']
      - name: resolution_category
        description: "Classification of resolution status"
        tests:
          - accepted_values:
              values: ['RESOLVED', 'CLOSED', 'ACTIVE', 'OTHER']
      - name: overall_quality_score
        description: "Calculated overall quality score for the user"
      - name: meeting_quality_percentage
        description: "Percentage of high-quality meetings hosted by user"
      - name: participation_quality_percentage
        description: "Percentage of high-quality participations by user"
