version: 2

models:
  - name: go_meeting_facts
    description: "Comprehensive meeting analytics and metrics fact table"
    columns:
      - name: meeting_fact_key
        description: "Surrogate key for meeting facts"
        tests:
          - unique
          - not_null
      - name: meeting_id
        description: "Unique identifier for the meeting"
        tests:
          - not_null
      - name: host_id
        description: "User ID of the meeting host"
        tests:
          - not_null
      - name: meeting_date
        description: "Date of the meeting"
        tests:
          - not_null
      - name: duration_minutes
        description: "Duration of the meeting in minutes"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1440
      - name: total_participants
        description: "Total number of participants in the meeting"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: process_status
        description: "Status of the data processing"
        tests:
          - accepted_values:
              values: ['SUCCESS', 'FAILED', 'PENDING']

  - name: go_participant_facts
    description: "Participant engagement and activity fact table"
    columns:
      - name: participant_fact_key
        description: "Surrogate key for participant facts"
        tests:
          - unique
          - not_null
      - name: participant_id
        description: "Unique identifier for the participant"
        tests:
          - not_null
      - name: meeting_id
        description: "Unique identifier for the meeting"
        tests:
          - not_null
      - name: participation_duration_minutes
        description: "Duration of participation in minutes"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: participation_percentage
        description: "Percentage of meeting duration participated"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 100
      - name: process_status
        description: "Status of the data processing"
        tests:
          - accepted_values:
              values: ['SUCCESS', 'FAILED', 'PENDING']

  - name: go_webinar_facts
    description: "Webinar performance metrics fact table"
    columns:
      - name: webinar_fact_key
        description: "Surrogate key for webinar facts"
        tests:
          - unique
          - not_null
      - name: webinar_id
        description: "Unique identifier for the webinar"
        tests:
          - not_null
      - name: host_id
        description: "User ID of the webinar host"
        tests:
          - not_null
      - name: registrants
        description: "Number of webinar registrants"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: actual_attendees
        description: "Number of actual webinar attendees"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: attendance_rate_percentage
        description: "Percentage of registrants who attended"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 100
      - name: process_status
        description: "Status of the data processing"
        tests:
          - accepted_values:
              values: ['SUCCESS', 'FAILED', 'PENDING']

  - name: go_billing_facts
    description: "Billing and financial data fact table"
    columns:
      - name: billing_fact_key
        description: "Surrogate key for billing facts"
        tests:
          - unique
          - not_null
      - name: event_id
        description: "Unique identifier for the billing event"
        tests:
          - not_null
      - name: user_id
        description: "User ID associated with the billing event"
        tests:
          - not_null
      - name: amount
        description: "Billing amount"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: transaction_status
        description: "Status of the transaction"
        tests:
          - accepted_values:
              values: ['SUCCESS', 'FAILED', 'PENDING', 'CANCELLED']
      - name: process_status
        description: "Status of the data processing"
        tests:
          - accepted_values:
              values: ['SUCCESS', 'FAILED', 'PENDING']

  - name: go_usage_facts
    description: "User usage patterns and statistics fact table"
    columns:
      - name: usage_fact_key
        description: "Surrogate key for usage facts"
        tests:
          - unique
          - not_null
      - name: usage_id
        description: "Unique identifier for the usage record"
        tests:
          - not_null
      - name: user_id
        description: "User ID associated with the usage"
        tests:
          - not_null
      - name: feature_name
        description: "Name of the feature used"
        tests:
          - not_null
      - name: usage_count
        description: "Number of times the feature was used"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: usage_intensity
        description: "Categorized usage intensity"
        tests:
          - accepted_values:
              values: ['Heavy', 'Moderate', 'Light', 'None']
      - name: process_status
        description: "Status of the data processing"
        tests:
          - accepted_values:
              values: ['SUCCESS', 'FAILED', 'PENDING']

  - name: go_quality_facts
    description: "Quality metrics and performance data fact table"
    columns:
      - name: quality_fact_key
        description: "Surrogate key for quality facts"
        tests:
          - unique
          - not_null
      - name: meeting_id
        description: "Unique identifier for the meeting"
        tests:
          - not_null
      - name: host_id
        description: "User ID of the meeting host"
        tests:
          - not_null
      - name: overall_quality_score
        description: "Overall quality score (0-100)"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 100
      - name: participation_quality_percentage
        description: "Participation quality as percentage"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 100
      - name: participation_quality_category
        description: "Categorized participation quality"
        tests:
          - accepted_values:
              values: ['High', 'Medium', 'Low']
      - name: process_status
        description: "Status of the data processing"
        tests:
          - accepted_values:
              values: ['SUCCESS', 'FAILED', 'PENDING']
