version: 2

models:
  - name: go_meeting_facts
    description: "Gold layer fact table for comprehensive meeting analytics and reporting"
    config:
      materialized: table
      cluster_by: ['meeting_date', 'host_id']
    columns:
      - name: meeting_fact_id
        description: "Unique identifier for meeting fact record"
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "Primary key for meetings from source system"
        tests:
          - not_null
      - name: host_id
        description: "Identifier for meeting host"
        tests:
          - not_null
      - name: duration_minutes
        description: "Meeting duration in minutes"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1440
      - name: participant_count
        description: "Total number of participants"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: engagement_score
        description: "Calculated engagement score based on feature usage"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100

  - name: go_participant_facts
    description: "Gold layer fact table for participant-level meeting analytics"
    config:
      materialized: table
      cluster_by: ['participation_date', 'meeting_id']
    columns:
      - name: participant_fact_id
        description: "Unique identifier for participant fact record"
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "Foreign key to meeting"
        tests:
          - not_null
      - name: participant_id
        description: "Unique identifier for participant"
        tests:
          - not_null
      - name: attendance_rate
        description: "Participant attendance rate as percentage of meeting duration"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1
      - name: attendance_duration
        description: "Duration of participant attendance in minutes"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

  - name: go_webinar_facts
    description: "Gold layer fact table for webinar analytics and performance metrics"
    config:
      materialized: table
      cluster_by: ['webinar_date', 'host_id']
    columns:
      - name: webinar_fact_id
        description: "Unique identifier for webinar fact record"
        tests:
          - not_null
          - unique
      - name: webinar_id
        description: "Primary key for webinars"
        tests:
          - not_null
      - name: attendance_rate
        description: "Webinar attendance rate (actual vs registered)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: registrants_count
        description: "Number of webinar registrants"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

  - name: go_billing_facts
    description: "Gold layer fact table for billing events and revenue analytics"
    config:
      materialized: table
      cluster_by: ['event_date', 'user_id']
    columns:
      - name: billing_fact_id
        description: "Unique identifier for billing fact record"
        tests:
          - not_null
          - unique
      - name: event_id
        description: "Primary key for billing events"
        tests:
          - not_null
      - name: amount
        description: "Billing amount"
        tests:
          - not_null
      - name: net_revenue_impact
        description: "Net revenue impact of the billing event"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

  - name: go_usage_facts
    description: "Gold layer fact table for feature usage analytics"
    config:
      materialized: table
      cluster_by: ['usage_date', 'meeting_id']
    columns:
      - name: usage_fact_id
        description: "Unique identifier for usage fact record"
        tests:
          - not_null
          - unique
      - name: usage_id
        description: "Primary key for usage records"
        tests:
          - not_null
      - name: usage_count
        description: "Number of times feature was used"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: usage_per_hour
        description: "Usage frequency per hour"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0

  - name: go_quality_facts
    description: "Gold layer fact table for data quality and support analytics"
    config:
      materialized: table
      cluster_by: ['quality_date', 'ticket_id']
    columns:
      - name: quality_fact_id
        description: "Unique identifier for quality fact record"
        tests:
          - not_null
          - unique
      - name: ticket_id
        description: "Primary key for support tickets"
        tests:
          - not_null
      - name: overall_quality_score
        description: "Overall quality score"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 5
      - name: audio_quality_score
        description: "Audio quality score"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 5
      - name: video_quality_score
        description: "Video quality score"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 5
