version: 2

models:
  - name: go_meeting_facts
    description: "Gold layer fact table containing meeting analytics and metrics"
    columns:
      - name: meeting_fact_key
        description: "Unique surrogate key for meeting facts"
        tests:
          - unique
          - not_null
      - name: meeting_id
        description: "Business key for meeting"
        tests:
          - not_null
      - name: host_id
        description: "ID of the meeting host"
        tests:
          - not_null
      - name: duration_minutes
        description: "Meeting duration in minutes"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1440
      - name: total_participants
        description: "Total number of participants in the meeting"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: engagement_rate
        description: "Percentage of engaged participants"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100

  - name: go_participant_facts
    description: "Gold layer fact table containing participant analytics and engagement metrics"
    columns:
      - name: participant_fact_key
        description: "Unique surrogate key for participant facts"
        tests:
          - unique
          - not_null
      - name: participant_id
        description: "Business key for participant"
        tests:
          - not_null
      - name: meeting_id
        description: "Business key for meeting"
        tests:
          - not_null
      - name: user_id
        description: "Business key for user"
        tests:
          - not_null
      - name: attendance_rate
        description: "Percentage of meeting attended"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100

  - name: go_webinar_facts
    description: "Gold layer fact table containing webinar analytics and metrics"
    columns:
      - name: webinar_fact_key
        description: "Unique surrogate key for webinar facts"
        tests:
          - unique
          - not_null
      - name: webinar_id
        description: "Business key for webinar"
        tests:
          - not_null
      - name: host_id
        description: "ID of the webinar host"
        tests:
          - not_null
      - name: total_registrants
        description: "Total number of webinar registrants"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

  - name: go_billing_facts
    description: "Gold layer fact table containing billing events and revenue analytics"
    columns:
      - name: billing_fact_key
        description: "Unique surrogate key for billing facts"
        tests:
          - unique
          - not_null
      - name: event_id
        description: "Business key for billing event"
        tests:
          - not_null
      - name: user_id
        description: "Business key for user"
        tests:
          - not_null
      - name: amount
        description: "Billing event amount"
        tests:
          - not_null

  - name: go_usage_facts
    description: "Gold layer fact table containing feature usage analytics"
    columns:
      - name: usage_fact_key
        description: "Unique surrogate key for usage facts"
        tests:
          - unique
          - not_null
      - name: usage_id
        description: "Business key for usage event"
        tests:
          - not_null
      - name: meeting_id
        description: "Business key for meeting"
        tests:
          - not_null
      - name: feature_name
        description: "Name of the feature used"
        tests:
          - not_null
      - name: usage_count
        description: "Number of times feature was used"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

  - name: go_quality_facts
    description: "Gold layer fact table containing data quality metrics across all silver tables"
    columns:
      - name: quality_fact_key
        description: "Unique surrogate key for quality facts"
        tests:
          - unique
          - not_null
      - name: table_name
        description: "Name of the source table"
        tests:
          - not_null
      - name: source_system
        description: "Source system identifier"
        tests:
          - not_null
      - name: total_records
        description: "Total number of records in source table"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: avg_quality_score
        description: "Average data quality score"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1
      - name: active_record_percentage
        description: "Percentage of active records"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: high_quality_percentage
        description: "Percentage of high quality records"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
