version: 2

models:
  - name: go_meeting_facts
    description: "Comprehensive meeting analytics and metrics fact table"
    columns:
      - name: meeting_fact_id
        description: "Unique identifier for meeting facts"
        tests:
          - unique
          - not_null
      - name: meeting_id
        description: "Unique identifier for the meeting"
        tests:
          - not_null
      - name: host_id
        description: "User ID of the meeting host"
        tests:
          - not_null
      - name: duration_minutes
        description: "Duration of the meeting in minutes"
        tests:
          - not_null
      - name: participant_count
        description: "Total number of participants in the meeting"
        tests:
          - not_null

  - name: go_participant_facts
    description: "Participant engagement and activity fact table"
    columns:
      - name: participant_fact_id
        description: "Unique identifier for participant facts"
        tests:
          - unique
          - not_null
      - name: participant_id
        description: "Unique identifier for the participant"
        tests:
          - not_null
      - name: meeting_id
        description: "Unique identifier for the meeting"
        tests:
          - not_null
      - name: attendance_duration
        description: "Duration of participation in minutes"
        tests:
          - not_null

  - name: go_webinar_facts
    description: "Webinar performance metrics fact table"
    columns:
      - name: webinar_fact_id
        description: "Unique identifier for webinar facts"
        tests:
          - unique
          - not_null
      - name: webinar_id
        description: "Unique identifier for the webinar"
        tests:
          - not_null
      - name: host_id
        description: "User ID of the webinar host"
        tests:
          - not_null
      - name: registrants_count
        description: "Number of webinar registrants"
        tests:
          - not_null

  - name: go_billing_facts
    description: "Billing and financial data fact table"
    columns:
      - name: billing_fact_id
        description: "Unique identifier for billing facts"
        tests:
          - unique
          - not_null
      - name: event_id
        description: "Unique identifier for the billing event"
        tests:
          - not_null
      - name: user_id
        description: "User ID associated with the billing event"
        tests:
          - not_null
      - name: amount
        description: "Billing amount"
        tests:
          - not_null

  - name: go_usage_facts
    description: "User usage patterns and statistics fact table"
    columns:
      - name: usage_fact_id
        description: "Unique identifier for usage facts"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "User ID associated with the usage"
        tests:
          - not_null
      - name: usage_date
        description: "Date of the usage"
        tests:
          - not_null

  - name: go_quality_facts
    description: "Quality metrics and performance data fact table"
    columns:
      - name: quality_fact_id
        description: "Unique identifier for quality facts"
        tests:
          - unique
          - not_null
      - name: meeting_id
        description: "Unique identifier for the meeting"
        tests:
          - not_null
      - name: participant_id
        description: "Unique identifier for the participant"
        tests:
          - not_null
