version: 2

sources:
  - name: bronze
    description: "Bronze layer containing raw data from various source systems"
    tables:
      - name: bz_users
        description: "Raw user data from Zoom platform"
        columns:
          - name: user_id
            description: "Unique identifier for users"
            tests:
              - not_null
              - unique
          - name: user_name
            description: "User display name"
          - name: email
            description: "User email address"
          - name: company
            description: "User company name"
          - name: plan_type
            description: "User subscription plan type"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system identifier"
            
      - name: bz_meetings
        description: "Raw meeting data from Zoom platform"
        columns:
          - name: meeting_id
            description: "Unique identifier for meetings"
            tests:
              - not_null
              - unique
          - name: host_id
            description: "User ID of meeting host"
          - name: meeting_topic
            description: "Meeting topic or title"
          - name: start_time
            description: "Meeting start timestamp"
          - name: end_time
            description: "Meeting end timestamp"
          - name: duration_minutes
            description: "Meeting duration in minutes"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system identifier"
            
      - name: bz_participants
        description: "Raw participant data from meetings"
        columns:
          - name: participant_id
            description: "Unique identifier for participants"
            tests:
              - not_null
              - unique
          - name: meeting_id
            description: "Meeting identifier"
          - name: user_id
            description: "User identifier for participant"
          - name: join_time
            description: "Participant join timestamp"
          - name: leave_time
            description: "Participant leave timestamp"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system identifier"
            
      - name: bz_feature_usage
        description: "Raw feature usage data"
        columns:
          - name: usage_id
            description: "Unique identifier for usage records"
            tests:
              - not_null
              - unique
          - name: meeting_id
            description: "Meeting identifier"
          - name: feature_name
            description: "Name of feature used"
          - name: usage_count
            description: "Number of times feature was used"
          - name: usage_date
            description: "Date of feature usage"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system identifier"
            
      - name: bz_webinars
        description: "Raw webinar data"
        columns:
          - name: webinar_id
            description: "Unique identifier for webinars"
            tests:
              - not_null
              - unique
          - name: host_id
            description: "User ID of webinar host"
          - name: webinar_topic
            description: "Webinar topic or title"
          - name: start_time
            description: "Webinar start timestamp"
          - name: end_time
            description: "Webinar end timestamp"
          - name: registrants
            description: "Number of webinar registrants"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system identifier"
            
      - name: bz_support_tickets
        description: "Raw support ticket data"
        columns:
          - name: ticket_id
            description: "Unique identifier for support tickets"
            tests:
              - not_null
              - unique
          - name: user_id
            description: "User identifier for ticket creator"
          - name: ticket_type
            description: "Type of support ticket"
          - name: resolution_status
            description: "Current status of ticket resolution"
          - name: open_date
            description: "Date when ticket was opened"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system identifier"
            
      - name: bz_licenses
        description: "Raw license data"
        columns:
          - name: license_id
            description: "Unique identifier for licenses"
            tests:
              - not_null
              - unique
          - name: license_type
            description: "Type of license"
          - name: assigned_to_user_id
            description: "User ID license is assigned to"
          - name: start_date
            description: "License start date"
          - name: end_date
            description: "License end date"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system identifier"
            
      - name: bz_billing_events
        description: "Raw billing event data"
        columns:
          - name: event_id
            description: "Unique identifier for billing events"
            tests:
              - not_null
              - unique
          - name: user_id
            description: "User identifier for billing event"
          - name: event_type
            description: "Type of billing event"
          - name: amount
            description: "Billing amount"
          - name: event_date
            description: "Date of billing event"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system identifier"

models:
  - name: si_process_audit
    description: "Process audit table for tracking ETL execution metrics"
    columns:
      - name: execution_id
        description: "Unique identifier for each execution"
        tests:
          - not_null
          - unique
      - name: pipeline_name
        description: "Name of the ETL pipeline"
        tests:
          - not_null
      - name: start_time
        description: "Pipeline execution start time"
      - name: end_time
        description: "Pipeline execution end time"
      - name: status
        description: "Execution status (RUNNING, COMPLETED, FAILED)"
        tests:
          - not_null
          - accepted_values:
              values: ['RUNNING', 'STARTED', 'COMPLETED', 'FAILED']
      - name: error_message
        description: "Error message if execution failed"
      - name: records_processed
        description: "Total number of records processed"
      - name: records_successful
        description: "Number of successfully processed records"
      - name: records_failed
        description: "Number of failed records"
      - name: processing_duration_seconds
        description: "Processing duration in seconds"
      - name: source_system
        description: "Source system name"
      - name: target_system
        description: "Target system name"
      - name: process_type
        description: "Type of process (ETL, Validation, etc.)"
      - name: user_executed
        description: "User who executed the process"
      - name: server_name
        description: "Server where process was executed"
      - name: memory_usage_mb
        description: "Memory usage in MB"
      - name: cpu_usage_percent
        description: "CPU usage percentage"
      - name: load_date
        description: "Date when record was loaded"
        tests:
          - not_null
      - name: update_date
        description: "Date when record was last updated"
        tests:
          - not_null
          
  - name: si_users
    description: "Silver layer users table with cleaned and validated data"
    columns:
      - name: user_id
        description: "Unique identifier for users"
        tests:
          - not_null
          - unique
      - name: user_name
        description: "Cleaned user display name"
        tests:
          - not_null
      - name: email
        description: "Validated and normalized email address"
        tests:
          - not_null
      - name: company
        description: "Cleaned company name"
      - name: plan_type
        description: "Standardized subscription plan type"
        tests:
          - not_null
          - accepted_values:
              values: ['FREE', 'PRO', 'BUSINESS', 'ENTERPRISE', 'UNKNOWN']
      - name: load_timestamp
        description: "Original load timestamp from bronze"
      - name: update_timestamp
        description: "Original update timestamp from bronze"
      - name: source_system
        description: "Source system identifier"
      - name: load_date
        description: "Date derived from load_timestamp"
        tests:
          - not_null
      - name: update_date
        description: "Date derived from update_timestamp"
        tests:
          - not_null
      - name: data_quality_score
        description: "Data quality score (0.0 to 1.0)"
        tests:
          - not_null
      - name: record_status
        description: "Record status (ACTIVE, ERROR)"
        tests:
          - not_null
          - accepted_values:
              values: ['ACTIVE', 'ERROR']
              
  - name: si_meetings
    description: "Silver layer meetings table with cleaned and validated data"
    columns:
      - name: meeting_id
        description: "Unique identifier for meetings"
        tests:
          - not_null
          - unique
      - name: host_id
        description: "User ID of meeting host"
        tests:
          - not_null
      - name: meeting_topic
        description: "Cleaned meeting topic"
      - name: start_time
        description: "Meeting start timestamp"
        tests:
          - not_null
      - name: end_time
        description: "Meeting end timestamp"
        tests:
          - not_null
      - name: duration_minutes
        description: "Meeting duration in minutes"
        tests:
          - not_null
      - name: load_timestamp
        description: "Original load timestamp from bronze"
      - name: update_timestamp
        description: "Original update timestamp from bronze"
      - name: source_system
        description: "Source system identifier"
      - name: load_date
        description: "Date derived from load_timestamp"
        tests:
          - not_null
      - name: update_date
        description: "Date derived from update_timestamp"
        tests:
          - not_null
      - name: data_quality_score
        description: "Data quality score (0.0 to 1.0)"
        tests:
          - not_null
      - name: record_status
        description: "Record status (ACTIVE, ERROR)"
        tests:
          - not_null
          - accepted_values:
              values: ['ACTIVE', 'ERROR']
