version: 2

sources:
  - name: bronze
    description: "Bronze layer containing raw data from source systems"
    tables:
      - name: bz_users
        description: "Raw user data from Zoom"
        columns:
          - name: user_id
            description: "Unique identifier for users"
            tests:
              - not_null
              - unique
          - name: email
            description: "User email address"
            tests:
              - not_null
      - name: bz_meetings
        description: "Raw meeting data from Zoom"
        columns:
          - name: meeting_id
            description: "Unique identifier for meetings"
            tests:
              - not_null
              - unique
      - name: bz_participants
        description: "Raw participant data from Zoom"
        columns:
          - name: participant_id
            description: "Unique identifier for participants"
            tests:
              - not_null
              - unique
      - name: bz_feature_usage
        description: "Raw feature usage data from Zoom"
        columns:
          - name: usage_id
            description: "Unique identifier for usage records"
            tests:
              - not_null
              - unique
      - name: bz_webinars
        description: "Raw webinar data from Zoom"
        columns:
          - name: webinar_id
            description: "Unique identifier for webinars"
            tests:
              - not_null
              - unique
      - name: bz_support_tickets
        description: "Raw support ticket data from Zoom"
        columns:
          - name: ticket_id
            description: "Unique identifier for support tickets"
            tests:
              - not_null
              - unique
      - name: bz_licenses
        description: "Raw license data from Zoom"
        columns:
          - name: license_id
            description: "Unique identifier for licenses"
            tests:
              - not_null
              - unique
      - name: bz_billing_events
        description: "Raw billing event data from Zoom"
        columns:
          - name: event_id
            description: "Unique identifier for billing events"
            tests:
              - not_null
              - unique

models:
  - name: si_process_audit
    description: "Process audit log for tracking ETL pipeline execution"
    columns:
      - name: execution_id
        description: "Unique identifier for each pipeline execution"
        tests:
          - not_null
          - unique
      - name: pipeline_name
        description: "Name of the pipeline being executed"
        tests:
          - not_null
      - name: status
        description: "Execution status (SUCCESS, FAILED, STARTED)"
        tests:
          - not_null
          - accepted_values:
              values: ['SUCCESS', 'FAILED', 'STARTED']

  - name: si_users
    description: "Cleaned and validated user data"
    columns:
      - name: user_id
        description: "Unique identifier for users"
        tests:
          - not_null
          - unique
      - name: user_name
        description: "User display name"
        tests:
          - not_null
      - name: email
        description: "User email address (validated and normalized)"
        tests:
          - not_null
          - unique
      - name: plan_type
        description: "User subscription plan type"
        tests:
          - not_null
          - accepted_values:
              values: ['Free', 'Pro', 'Business', 'Enterprise']
      - name: data_quality_score
        description: "Data quality score (0.0 to 1.0)"
        tests:
          - not_null
      - name: record_status
        description: "Record status (active or error)"
        tests:
          - not_null
          - accepted_values:
              values: ['active', 'error']

  - name: si_meetings
    description: "Cleaned and validated meeting data"
    columns:
      - name: meeting_id
        description: "Unique identifier for meetings"
        tests:
          - not_null
          - unique
      - name: host_id
        description: "User ID of the meeting host"
        tests:
          - not_null
          - relationships:
              to: ref('si_users')
              field: user_id
      - name: duration_minutes
        description: "Meeting duration in minutes"
        tests:
          - not_null

  - name: si_participants
    description: "Cleaned and validated participant data"
    columns:
      - name: participant_id
        description: "Unique identifier for participants"
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "Meeting ID for the participation"
        tests:
          - not_null
          - relationships:
              to: ref('si_meetings')
              field: meeting_id
      - name: user_id
        description: "User ID of the participant"
        tests:
          - relationships:
              to: ref('si_users')
              field: user_id

  - name: si_feature_usage
    description: "Cleaned and validated feature usage data"
    columns:
      - name: usage_id
        description: "Unique identifier for usage records"
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "Meeting ID where feature was used"
        tests:
          - not_null
          - relationships:
              to: ref('si_meetings')
              field: meeting_id
      - name: feature_name
        description: "Name of the feature used"
        tests:
          - not_null
          - accepted_values:
              values: ['Screen Sharing', 'Chat', 'Recording', 'Whiteboard', 'Virtual Background']
      - name: usage_count
        description: "Number of times feature was used"
        tests:
          - not_null

  - name: si_webinars
    description: "Cleaned and validated webinar data"
    columns:
      - name: webinar_id
        description: "Unique identifier for webinars"
        tests:
          - not_null
          - unique
      - name: host_id
        description: "User ID of the webinar host"
        tests:
          - not_null
          - relationships:
              to: ref('si_users')
              field: user_id
      - name: registrants
        description: "Number of webinar registrants"
        tests:
          - not_null

  - name: si_support_tickets
    description: "Cleaned and validated support ticket data"
    columns:
      - name: ticket_id
        description: "Unique identifier for support tickets"
        tests:
          - not_null
          - unique
      - name: user_id
        description: "User ID who created the ticket"
        tests:
          - not_null
          - relationships:
              to: ref('si_users')
              field: user_id
      - name: ticket_type
        description: "Type of support ticket"
        tests:
          - not_null
          - accepted_values:
              values: ['Audio Issue', 'Video Issue', 'Connectivity', 'Billing Inquiry', 'Feature Request', 'Account Access']
      - name: resolution_status
        description: "Current status of the ticket"
        tests:
          - not_null
          - accepted_values:
              values: ['Open', 'In Progress', 'Pending Customer', 'Closed', 'Resolved']

  - name: si_licenses
    description: "Cleaned and validated license data"
    columns:
      - name: license_id
        description: "Unique identifier for licenses"
        tests:
          - not_null
          - unique
      - name: license_type
        description: "Type of license"
        tests:
          - not_null
          - accepted_values:
              values: ['Pro', 'Business', 'Enterprise', 'Education']
      - name: assigned_to_user_id
        description: "User ID the license is assigned to"
        tests:
          - relationships:
              to: ref('si_users')
              field: user_id

  - name: si_billing_events
    description: "Cleaned and validated billing event data"
    columns:
      - name: event_id
        description: "Unique identifier for billing events"
        tests:
          - not_null
          - unique
      - name: user_id
        description: "User ID associated with the billing event"
        tests:
          - not_null
          - relationships:
              to: ref('si_users')
              field: user_id
      - name: event_type
        description: "Type of billing event"
        tests:
          - not_null
          - accepted_values:
              values: ['Subscription Fee', 'Subscription Renewal', 'Add-on Purchase', 'Refund']
      - name: amount
        description: "Billing amount"
        tests:
          - not_null
