version: 2

sources:
  - name: bronze
    description: "Bronze layer containing raw data from Zoom systems"
    tables:
      - name: bz_users
        description: "Raw user data from Zoom"
      - name: bz_meetings
        description: "Raw meeting data from Zoom"
      - name: bz_participants
        description: "Raw participant data from Zoom"
      - name: bz_feature_usage
        description: "Raw feature usage data from Zoom"
      - name: bz_webinars
        description: "Raw webinar data from Zoom"
      - name: bz_support_tickets
        description: "Raw support ticket data from Zoom"
      - name: bz_licenses
        description: "Raw license data from Zoom"
      - name: bz_billing_events
        description: "Raw billing event data from Zoom"

models:
  - name: si_process_audit
    description: "Process audit table for tracking ETL execution"
    columns:
      - name: execution_id
        description: "Unique identifier for each execution"
        tests:
          - not_null
          - unique
      - name: pipeline_name
        description: "Name of the ETL pipeline"
        tests:
          - not_null
      - name: start_time
        description: "Pipeline start timestamp"
        tests:
          - not_null
      - name: status
        description: "Execution status (SUCCESS/FAILURE)"
        tests:
          - not_null
          - accepted_values:
              values: ['SUCCESS', 'FAILURE', 'STARTED', 'IN_PROGRESS']
              
  - name: si_users
    description: "Silver layer users table with cleaned and validated data"
    columns:
      - name: user_id
        description: "Unique identifier for users"
        tests:
          - not_null
          - unique
      - name: user_name
        description: "User display name (trimmed)"
        tests:
          - not_null
      - name: email
        description: "User email address (lowercase, trimmed)"
        tests:
          - not_null
          - unique
      - name: plan_type
        description: "User subscription plan (validated domain)"
        tests:
          - not_null
          - accepted_values:
              values: ['Free', 'Pro', 'Business', 'Enterprise']
      - name: record_status
        description: "Record status (active/error)"
        tests:
          - not_null
          - accepted_values:
              values: ['active', 'error']
              
  - name: si_meetings
    description: "Silver layer meetings table with cleaned and validated data"
    columns:
      - name: meeting_id
        description: "Unique identifier for meetings"
        tests:
          - not_null
          - unique
      - name: host_id
        description: "Meeting host user ID"
        tests:
          - not_null
      - name: start_time
        description: "Meeting start time"
        tests:
          - not_null
      - name: end_time
        description: "Meeting end time"
        tests:
          - not_null
      - name: record_status
        description: "Record status (active/error)"
        tests:
          - not_null
          - accepted_values:
              values: ['active', 'error']
              
  - name: si_participants
    description: "Silver layer participants table with cleaned and validated data"
    columns:
      - name: participant_id
        description: "Unique identifier for participants"
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "Associated meeting ID"
        tests:
          - not_null
      - name: join_time
        description: "Time participant joined"
        tests:
          - not_null
      - name: leave_time
        description: "Time participant left"
        tests:
          - not_null
      - name: record_status
        description: "Record status (active/error)"
        tests:
          - not_null
          - accepted_values:
              values: ['active', 'error']
              
  - name: si_feature_usage
    description: "Silver layer feature usage table with cleaned and validated data"
    columns:
      - name: usage_id
        description: "Unique identifier for usage records"
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "Associated meeting ID"
        tests:
          - not_null
      - name: feature_name
        description: "Name of the feature used (validated domain)"
        tests:
          - not_null
          - accepted_values:
              values: ['Screen Sharing', 'Chat', 'Recording', 'Whiteboard', 'Virtual Background', 'Other']
      - name: usage_count
        description: "Number of times feature was used (>=0)"
        tests:
          - not_null
      - name: usage_date
        description: "Date of feature usage"
        tests:
          - not_null
      - name: record_status
        description: "Record status (active/error)"
        tests:
          - not_null
          - accepted_values:
              values: ['active', 'error']
              
  - name: si_webinars
    description: "Silver layer webinars table with cleaned and validated data"
    columns:
      - name: webinar_id
        description: "Unique identifier for webinars"
        tests:
          - not_null
          - unique
      - name: host_id
        description: "Webinar host user ID"
        tests:
          - not_null
      - name: webinar_topic
        description: "Webinar topic/title (trimmed)"
        tests:
          - not_null
      - name: start_time
        description: "Webinar start time"
        tests:
          - not_null
      - name: end_time
        description: "Webinar end time"
        tests:
          - not_null
      - name: registrants
        description: "Number of registrants (>=0)"
        tests:
          - not_null
      - name: record_status
        description: "Record status (active/error)"
        tests:
          - not_null
          - accepted_values:
              values: ['active', 'error']
              
  - name: si_support_tickets
    description: "Silver layer support tickets table with cleaned and validated data"
    columns:
      - name: ticket_id
        description: "Unique identifier for support tickets"
        tests:
          - not_null
          - unique
      - name: user_id
        description: "User who created the ticket"
        tests:
          - not_null
      - name: ticket_type
        description: "Type of support ticket (validated domain)"
        tests:
          - not_null
          - accepted_values:
              values: ['Audio Issue', 'Video Issue', 'Connectivity', 'Billing Inquiry', 'Feature Request', 'Account Access', 'Other']
      - name: resolution_status
        description: "Current status of the ticket (validated domain)"
        tests:
          - not_null
          - accepted_values:
              values: ['Open', 'In Progress', 'Pending Customer', 'Closed', 'Resolved']
      - name: open_date
        description: "Date ticket was opened"
        tests:
          - not_null
      - name: record_status
        description: "Record status (active/error)"
        tests:
          - not_null
          - accepted_values:
              values: ['active', 'error']
              
  - name: si_licenses
    description: "Silver layer licenses table with cleaned and validated data"
    columns:
      - name: license_id
        description: "Unique identifier for licenses"
        tests:
          - not_null
          - unique
      - name: license_type
        description: "Type of license (validated domain)"
        tests:
          - not_null
          - accepted_values:
              values: ['Pro', 'Business', 'Enterprise', 'Education']
      - name: start_date
        description: "License start date"
        tests:
          - not_null
      - name: end_date
        description: "License end date"
        tests:
          - not_null
      - name: record_status
        description: "Record status (active/error)"
        tests:
          - not_null
          - accepted_values:
              values: ['active', 'error']
              
  - name: si_billing_events
    description: "Silver layer billing events table with cleaned and validated data"
    columns:
      - name: event_id
        description: "Unique identifier for billing events"
        tests:
          - not_null
          - unique
      - name: user_id
        description: "User associated with billing event"
        tests:
          - not_null
      - name: event_type
        description: "Type of billing event (validated domain)"
        tests:
          - not_null
          - accepted_values:
              values: ['Subscription Fee', 'Subscription Renewal', 'Add-on Purchase', 'Refund', 'Other']
      - name: amount
        description: "Billing amount (>=0)"
        tests:
          - not_null
      - name: event_date
        description: "Date of billing event"
        tests:
          - not_null
      - name: record_status
        description: "Record status (active/error)"
        tests:
          - not_null
          - accepted_values:
              values: ['active', 'error']
