version: 2

sources:
  - name: bronze
    description: "Bronze layer containing raw data from source systems"
    tables:
      - name: bz_users
        description: "Raw user data from Zoom"
        columns:
          - name: user_id
            description: "Unique identifier for users"
            tests:
              - not_null
              - unique
          - name: email
            description: "User email address"
            tests:
              - not_null
      
      - name: bz_meetings
        description: "Raw meeting data from Zoom"
        columns:
          - name: meeting_id
            description: "Unique identifier for meetings"
            tests:
              - not_null
              - unique
          - name: host_id
            description: "Meeting host user ID"
            tests:
              - not_null
      
      - name: bz_participants
        description: "Raw participant data from Zoom"
        columns:
          - name: participant_id
            description: "Unique identifier for participants"
            tests:
              - not_null
              - unique
          - name: meeting_id
            description: "Associated meeting ID"
            tests:
              - not_null
      
      - name: bz_feature_usage
        description: "Raw feature usage data from Zoom"
        columns:
          - name: usage_id
            description: "Unique identifier for usage records"
            tests:
              - not_null
              - unique
      
      - name: bz_webinars
        description: "Raw webinar data from Zoom"
        columns:
          - name: webinar_id
            description: "Unique identifier for webinars"
            tests:
              - not_null
              - unique
      
      - name: bz_support_tickets
        description: "Raw support ticket data from Zoom"
        columns:
          - name: ticket_id
            description: "Unique identifier for support tickets"
            tests:
              - not_null
              - unique
      
      - name: bz_licenses
        description: "Raw license data from Zoom"
        columns:
          - name: license_id
            description: "Unique identifier for licenses"
            tests:
              - not_null
              - unique
      
      - name: bz_billing_events
        description: "Raw billing event data from Zoom"
        columns:
          - name: event_id
            description: "Unique identifier for billing events"
            tests:
              - not_null
              - unique

models:
  - name: si_process_audit
    description: "Process audit table for tracking ETL execution"
    columns:
      - name: execution_id
        description: "Unique identifier for each execution"
        tests:
          - not_null
          - unique
      - name: pipeline_name
        description: "Name of the ETL pipeline"
        tests:
          - not_null
      - name: status
        description: "Execution status"
        tests:
          - not_null
          - accepted_values:
              values: ['RUNNING', 'SUCCESS', 'FAILED']
  
  - name: si_users
    description: "Cleaned and validated user data"
    columns:
      - name: user_id
        description: "Unique identifier for users"
        tests:
          - not_null
          - unique
      - name: email
        description: "User email address (validated and cleaned)"
        tests:
          - not_null
      - name: data_quality_score
        description: "Data quality score (0.0 to 1.0)"
        tests:
          - not_null
      - name: record_status
        description: "Record status indicator"
        tests:
          - not_null
          - accepted_values:
              values: ['active', 'error']
  
  - name: si_meetings
    description: "Cleaned and validated meeting data"
    columns:
      - name: meeting_id
        description: "Unique identifier for meetings"
        tests:
          - not_null
          - unique
      - name: host_id
        description: "Meeting host user ID"
        tests:
          - not_null
      - name: data_quality_score
        description: "Data quality score (0.0 to 1.0)"
        tests:
          - not_null
      - name: record_status
        description: "Record status indicator"
        tests:
          - not_null
          - accepted_values:
              values: ['active', 'error']
  
  - name: si_participants
    description: "Cleaned and validated participant data"
    columns:
      - name: participant_id
        description: "Unique identifier for participants"
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "Associated meeting ID"
        tests:
          - not_null
      - name: data_quality_score
        description: "Data quality score (0.0 to 1.0)"
        tests:
          - not_null
      - name: record_status
        description: "Record status indicator"
        tests:
          - not_null
          - accepted_values:
              values: ['active', 'error']
  
  - name: si_feature_usage
    description: "Cleaned and validated feature usage data"
    columns:
      - name: usage_id
        description: "Unique identifier for usage records"
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "Associated meeting ID"
        tests:
          - not_null
      - name: feature_name
        description: "Standardized feature name"
        tests:
          - not_null
          - accepted_values:
              values: ['Screen Sharing', 'Chat', 'Recording', 'Whiteboard', 'Virtual Background', 'Other']
      - name: data_quality_score
        description: "Data quality score (0.0 to 1.0)"
        tests:
          - not_null
      - name: record_status
        description: "Record status indicator"
        tests:
          - not_null
          - accepted_values:
              values: ['active', 'error']
  
  - name: si_webinars
    description: "Cleaned and validated webinar data"
    columns:
      - name: webinar_id
        description: "Unique identifier for webinars"
        tests:
          - not_null
          - unique
      - name: host_id
        description: "Webinar host user ID"
        tests:
          - not_null
      - name: data_quality_score
        description: "Data quality score (0.0 to 1.0)"
        tests:
          - not_null
      - name: record_status
        description: "Record status indicator"
        tests:
          - not_null
          - accepted_values:
              values: ['active', 'error']
  
  - name: si_support_tickets
    description: "Cleaned and validated support ticket data"
    columns:
      - name: ticket_id
        description: "Unique identifier for support tickets"
        tests:
          - not_null
          - unique
      - name: user_id
        description: "Associated user ID"
        tests:
          - not_null
      - name: ticket_type
        description: "Standardized ticket type"
        tests:
          - not_null
          - accepted_values:
              values: ['Audio Issue', 'Video Issue', 'Connectivity', 'Billing Inquiry', 'Feature Request', 'Account Access', 'Other']
      - name: resolution_status
        description: "Standardized resolution status"
        tests:
          - not_null
          - accepted_values:
              values: ['Open', 'In Progress', 'Pending Customer', 'Closed', 'Resolved']
      - name: data_quality_score
        description: "Data quality score (0.0 to 1.0)"
        tests:
          - not_null
      - name: record_status
        description: "Record status indicator"
        tests:
          - not_null
          - accepted_values:
              values: ['active', 'error']
  
  - name: si_licenses
    description: "Cleaned and validated license data"
    columns:
      - name: license_id
        description: "Unique identifier for licenses"
        tests:
          - not_null
          - unique
      - name: license_type
        description: "Standardized license type"
        tests:
          - not_null
          - accepted_values:
              values: ['Pro', 'Business', 'Enterprise', 'Education']
      - name: data_quality_score
        description: "Data quality score (0.0 to 1.0)"
        tests:
          - not_null
      - name: record_status
        description: "Record status indicator"
        tests:
          - not_null
          - accepted_values:
              values: ['active', 'error']
  
  - name: si_billing_events
    description: "Cleaned and validated billing event data"
    columns:
      - name: event_id
        description: "Unique identifier for billing events"
        tests:
          - not_null
          - unique
      - name: user_id
        description: "Associated user ID"
        tests:
          - not_null
      - name: event_type
        description: "Standardized event type"
        tests:
          - not_null
          - accepted_values:
              values: ['Subscription Fee', 'Subscription Renewal', 'Add-on Purchase', 'Refund', 'Other']
      - name: amount
        description: "Event amount (validated >= 0)"
        tests:
          - not_null
      - name: data_quality_score
        description: "Data quality score (0.0 to 1.0)"
        tests:
          - not_null
      - name: record_status
        description: "Record status indicator"
        tests:
          - not_null
          - accepted_values:
              values: ['active', 'error']
  
  - name: si_data_quality_errors
    description: "Data quality error tracking table"
    columns:
      - name: error_id
        description: "Unique identifier for errors"
        tests:
          - not_null
          - unique
      - name: source_table
        description: "Source table where error occurred"
        tests:
          - not_null
      - name: error_type
        description: "Type of data quality error"
        tests:
          - not_null
      - name: severity_level
        description: "Error severity level"
        tests:
          - not_null
          - accepted_values:
              values: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']
